spring.application.name=forum-promotion
server.port=8086
spring.mongodb.uri=mongodb://localhost:27017/forum_db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=localhost:${spring.application.name}:${server.port}

