spring.application.name=watchparty-chat
server.port=8084
spring.mongodb.uri=mongodb://localhost:27017/watchparty_db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=localhost:${spring.application.name}:${server.port}
