spring.application.name=cinema-reservation
server.port=8085
spring.mongodb.uri=mongodb://localhost:27017/cinema_db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=localhost:${spring.application.name}:${server.port}

